[package]
name = "unipush-backend"
version = "0.1.0"
authors = ["Singee <git@singee.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
